site_name: eml_parser
site_url: https://github.com/GOVCERT-LU/eml_parser
repo_url: https://github.com/GOVCERT-LU/eml_parser


theme:
  name: "material"
  font: false

plugins:
- search

watch:
  - eml_parser

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - admonition
